ServerReservation/Controllers/RequestController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ServerReservation.Data;
using ServerReservation.Models;

namespace ServerReservation.Controllers
{
    [Authorize]
    public class RequestController : Controller
    {
        private readonly ApplicationDbContext _context;

        public RequestController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Request
        public async Task<IActionResult> Index()
        {
            var applicationDbContext = _context.Requests.Include(r => r.ApprovedByUser).Include(r => r.RequestedByUser).Include(r => r.Server);
            return View(await applicationDbContext.ToListAsync());
        }

        // GET: Request/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var request = await _context.Requests
                .Include(r => r.ApprovedByUser)
                .Include(r => r.RequestedByUser)
                .Include(r => r.Server)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (request == null)
            {
                return NotFound();
            }

            return View(request);
        }

        // GET: Request/Create
        public IActionResult Create(int? id)
        {
            var selectedServerId = id;
            if (selectedServerId == null)
            {
                ViewData["ApprovedByUserId"] = new SelectList(_context.Users, "Id", "Details");
                ViewData["RequestedByUserId"] = new SelectList(_context.Users, "Id", "Details");
                ViewData["ServerId"] = new SelectList(_context.Servers, "Id", "Details");
                return View();
            }
            else
            {
                ViewData["SelectedServerId"] = selectedServerId;
                ViewData["ApprovedByUserId"] = new SelectList(_context.Users, "Id", "Details");
                ViewData["RequestedByUserId"] = new SelectList(_context.Users, "Id", "Details");
                ViewData["ServerId"] = new SelectList(_context.Servers.Where(i => i.Id == selectedServerId), "Id", "Details");
                return View();
            }
        }

        // POST: Request/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(int? selectedServerId, [Bind("Id,Timestamp,StartDate,EndDate,IsNewServer,ServerId,RequestedByEmployeeId,RequestedByEmployeeName,RequestedByUserId,RequestJustification,ApprovalStatus,ApprovedByEmployeeId,ApprovedByEmployeeName,ApprovedByUserId,ApprovalComment")] Request request)
        {
            if (ModelState.IsValid)
            {
                request.ApprovalStatus = ApprovalStatus.Pending;
                _context.Add(request);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["ApprovedByUserId"] = new SelectList(_context.Users, "Id", "Details", request.ApprovedByUserId);
            ViewData["RequestedByUserId"] = new SelectList(_context.Users, "Id", "Details", request.RequestedByUserId);
            ViewData["ServerId"] = new SelectList(_context.Servers, "Id", "Details", request.ServerId);
            return View(request);
        }

        // GET: Request/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var request = await _context.Requests.FindAsync(id);
            if (request == null)
            {
                return NotFound();
            }
            ViewData["ApprovedByUserId"] = new SelectList(_context.Users, "Id", "Details", request.ApprovedByUserId);
            ViewData["RequestedByUserId"] = new SelectList(_context.Users, "Id", "Details", request.RequestedByUserId);
            ViewData["ServerId"] = new SelectList(_context.Servers, "Id", "Details", request.ServerId);
            return View(request);
        }

        // POST: Request/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Timestamp,StartDate,EndDate,IsNewServer,ServerId,RequestedByEmployeeId,RequestedByEmployeeName,RequestedByUserId,RequestJustification,ApprovalStatus,ApprovedByEmployeeId,ApprovedByEmployeeName,ApprovedByUserId,ApprovalComment")] Request request)
        {
            if (id != request.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(request);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!RequestExists(request.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["ApprovedByUserId"] = new SelectList(_context.Users, "Id", "Details", request.ApprovedByUserId);
            ViewData["RequestedByUserId"] = new SelectList(_context.Users, "Id", "Details", request.RequestedByUserId);
            ViewData["ServerId"] = new SelectList(_context.Servers, "Id", "Details", request.ServerId);
            return View(request);
        }

        // GET: Request/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var request = await _context.Requests
                .Include(r => r.ApprovedByUser)
                .Include(r => r.RequestedByUser)
                .Include(r => r.Server)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (request == null)
            {
                return NotFound();
            }

            return View(request);
        }

        // POST: Request/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var request = await _context.Requests.FindAsync(id);
            _context.Requests.Remove(request);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool RequestExists(int id)
        {
            return _context.Requests.Any(e => e.Id == id);
        }
    }
}

ServerReservation/Controllers/ServerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Text.RegularExpressions;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json;
using NUnit.Framework;
using Renci.SshNet;
using ServerReservation.Data;
using ServerReservation.Models;

namespace ServerReservation.Controllers
{
    [Authorize]
    public class ServerController : Controller
    {
        private readonly ApplicationDbContext _context;

        private SshClient client;
        private static string username = "username";// TODO: Enter your sftp username here
        private static string password = "password";// TODO: Enter your sftp password here

        public ServerController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Server
        [AllowAnonymous]
        public async Task<IActionResult> Index()
        {
            return View(await _context.Servers.ToListAsync());
        }

        // GET: Select
        public async Task<IActionResult> Select()
        {
            return View(await _context.Servers.ToListAsync());
        }

        // GET: Server/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var server = await _context.Servers
                .FirstOrDefaultAsync(m => m.Id == id);
            if (server == null)
            {
                return NotFound();
            }

            return View(server);
        }

        // GET: Server/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Server/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Server server)
        {
            if (ModelState.IsValid)
            {
                _context.Add(server);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(server);
        }

        // GET: Server/CreateRequest
        public IActionResult CreateRequest()
        {
            return View();
        }

        // POST: Server/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> CreateRequest(Server server)
        {
            if (ModelState.IsValid)
            {
                _context.Add(server);
                await _context.SaveChangesAsync();

                return RedirectToAction("Create", "Request", new { id = server.Id });
            }
            return View(server);
        }

        // GET: Server/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var server = await _context.Servers.FindAsync(id);
            if (server == null)
            {
                return NotFound();
            }
            return View(server);
        }

        // POST: Server/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, Server server)
        {
            if (id != server.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(server);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ServerExists(server.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(server);
        }

        // GET: Server/Edit/5
        public async Task<IActionResult> EditRequest(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var server = await _context.Servers.FindAsync(id);
            if (server == null)
            {
                return NotFound();
            }
            return View(server);

        }

        // POST: Server/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> EditRequest(int id, Server server)
        {
            if (id != server.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(server);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ServerExists(server.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction("Create", "Request", new { id = server.Id });
            }
            return View(server);
        }

        // GET: Server/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var server = await _context.Servers
                .FirstOrDefaultAsync(m => m.Id == id);
            if (server == null)
            {
                return NotFound();
            }

            return View(server);
        }

        // POST: Server/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var server = await _context.Servers.FindAsync(id);
            _context.Servers.Remove(server);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ServerExists(int id)
        {
            return _context.Servers.Any(e => e.Id == id);
        }

        public async Task<IActionResult> Download(string IPv4Address)
        {
            if (string.IsNullOrEmpty(IPv4Address))
            {
                return NotFound();
            }

            Response.Headers.Add("Content-Disposition", "attachment; filename=Default.rdp");
            return new FileContentResult(Encoding.UTF8.GetBytes("full address:s:" + IPv4Address), "text/rdp");
        }


        public void SSH(string host)
        {
            string fileName = "install.bat";//TODO: "install.bat" is the name of the file which should be located in your project root directory.

            UploadFile(host, fileName);
            ExecuteCommandAsync(host);
        }

        private void UploadFile(string host, string fileName)
        {
            var connectionInfo = new ConnectionInfo(host, "sftp", new PasswordAuthenticationMethod(username, password));
            // Upload File
            using (var sftp = new SftpClient(connectionInfo))
            {
                sftp.Connect();
                sftp.ChangeDirectory("/MyFolder");//TODO: Change Directory
                using (var uplfileStream = System.IO.File.OpenRead(fileName))
                {
                    sftp.UploadFile(uplfileStream, fileName, true);
                }
                sftp.Disconnect();
            }
        }

        private void ExecuteCommandAsync(string host)
        {

            using (var client = new SshClient(host, username, password))
            {
                #region SshCommand RunCommand Result
                client.Connect();

                var command = client.RunCommand("install.bat");//TODO: Customize command
                var result = command.Result;

                client.Disconnect();
                #endregion


            }
        }

    }
}

ServerReservation/Views/Request/Create.cshtml
@using Microsoft.AspNetCore.Identity
@using Microsoft.AspNetCore.Identity.EntityFrameworkCore
@using ServerReservation.Areas.Identity.Models
@inject SignInManager<ApplicationUser> SignInManager
@inject UserManager<ApplicationUser> UserManager
@model ServerReservation.Models.Request

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
    var user = await UserManager.GetUserAsync(User);
}

<h2>Request - Create</h2>
<hr />


<div class="d-flex">
    <form asp-action="Create" asp-route-id="">

        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <!-- #region Account information -->
        <div class="card bg-light mb-3">
            @if (SignInManager.IsSignedIn(User))
            {
                <div class="card-header">
                    <div class="row">
                        <h6 class="float-left col">
                            The following account information will be recorded when you submit this form:
                        </h6>
                        <div class="float-right">
                            Not you?<br /><a asp-area="Identity" asp-page="/Account/Logout">Logout</a>
                            <!-- Attention: -->
                        </div>
                    </div>
                </div>
                <div class="card-body">
                    <dl class="row">
                        @if (!string.IsNullOrEmpty(@user.FullName))
                        {
                            <dt class="col-5">
                                <h6>Name:</h6>
                            </dt>
                            <dd class="col-7">
                                <div class=""> @user.FullName</div>
                            </dd>
                        }
                        @if (!string.IsNullOrEmpty(@user.EmployeeId))
                        {
                            <dt class="col-5">
                                <h6>Employee Id:</h6>
                            </dt>
                            <dd class="col-7">
                                <div class=""> @user.EmployeeId</div>
                            </dd>
                        }
                        @if (!string.IsNullOrEmpty(@user.Email))
                        {
                            <dt class="col-5">
                                <h6>Email:</h6>
                            </dt>
                            <dd class="col-7">
                                <div class=""> @user.Email</div>
                            </dd>
                        }
                        @if (!string.IsNullOrEmpty(@user.PhoneNumber))
                        {
                            <dt class="col-5">
                                <h6>Phone Number:</h6>
                            </dt>
                            <dd class="col-7">
                                <div class="">@user.PhoneNumber</div>
                            </dd>
                        }
                    </dl>
                    <div class="form-group">
                        <label asp-for="RequestedByUserId" class="control-label sr-only"></label>
                        <input asp-for="RequestedByUserId" class="form-control" value="@user.Id" type="hidden" />
                        <span asp-validation-for="RequestedByUserId" class="text-danger"></span>
                    </div>
                </div>

            }
            else
            {
                <div class="card-body">
                    <div class="form-group">
                        <label asp-for="RequestedByEmployeeName" class="control-label"></label>
                        <input asp-for="RequestedByEmployeeName" class="form-control" required />
                        <span asp-validation-for="RequestedByEmployeeName" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="RequestedByEmployeeId" class="control-label"></label>
                        <input asp-for="RequestedByEmployeeId" class="form-control" required />
                        <span asp-validation-for="RequestedByEmployeeId" class="text-danger"></span>
                    </div>

                </div>
            }
        </div>
        <!-- #endregion Account information-->
        <!-- #region Request Details -->
        <div class="card bg-light mb-3">
            <div class="card-body">
                <a asp-controller="Server" asp-action="EditRequest" asp-route-id="@ViewBag.SelectedServerId" class="rr">Edit</a>
                <div class="form-group">
                    <label asp-for="ServerId" class="control-label"></label>
                    <select asp-for="ServerId" class="form-control not-allowed" asp-items="ViewBag.ServerId" readonly></select>


                </div>
                <div class="form-row">
                    <div class="form-group col">
                        <label asp-for="StartDate" class="control-label"></label>
                        <input asp-for="StartDate" type="text" value="" id="StartDate" class="form-control" />
                        <span asp-validation-for="StartDate" class="text-danger"></span>
                    </div>
                    <div class="form-group col">
                        <label asp-for="EndDate" class="control-label"></label>
                        <input asp-for="EndDate" type="text" value="" id="EndDate" class="form-control" />
                        <span asp-validation-for="EndDate" class="text-danger"></span>
                    </div>
                </div>
            </div>
            <div class="card-footer">
                <div class="form-group">
                    <label asp-for="RequestJustification" class="control-label"></label>
                    <textarea asp-for="RequestJustification" class="form-control"></textarea>
                    <span asp-validation-for="RequestJustification" class="text-danger"></span>
                </div>
            </div>
        </div>
        <!-- #endregion Request Details-->

        <div class="form-group">
            <a asp-controller="Server" asp-action="Select">Back to List</a>
            <input type="submit" value="Create" class="btn btn-primary rr" />
        </div>

    </form>
</div>


@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

ServerReservation/Views/Request/Delete.cshtml
@model ServerReservation.Models.Request

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Request - Delete</h2>

<h5>Are you sure you want to delete this?</h5>
<hr />
<div>

    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Timestamp)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Timestamp)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.StartDate)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.StartDate)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.EndDate)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.EndDate)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.IsNewServer)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.IsNewServer)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Server)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Server.Id)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.RequestedByEmployeeId)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.RequestedByEmployeeId)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.RequestedByEmployeeName)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.RequestedByEmployeeName)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.RequestedByUser)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.RequestedByUser.Id)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.RequestJustification)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.RequestJustification)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.ApprovalStatus)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.ApprovalStatus)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.ApprovedByEmployeeId)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.ApprovedByEmployeeId)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.ApprovedByEmployeeName)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.ApprovedByEmployeeName)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.ApprovedByUser)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.ApprovedByUser.Id)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.ApprovalComment)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.ApprovalComment)
        </dd>
    </dl>

    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

ServerReservation/Views/Request/Index.cshtml
@model IEnumerable<ServerReservation.Models.Request>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="col-4  pl-0"><h1>Requests</h1></div>
<hr />

<a asp-controller="Server" asp-action="Select" class="btn btn-primary btn-sm rr">Create New</a>

<select id="StatusFilter" asp-items="Html.GetEnumSelectList<ServerReservation.Models.ApprovalStatus>()"
        class="selectpicker SelectListWhite SelectList p-small ml-2 mr-2 rr"></select>

<div id="reportrange" class="reportrange r">
    <i class="fa fa-calendar "></i>&nbsp;
    <span></span>
    <input type="hidden" id="start" name="start">
    <input type="hidden" id="end" name="end">
    <i class="fa fa-caret-down mt-1 ml-1 r"></i>
</div>


<table id="requestTable" class="table table-striped table-bordered table-hover nowrap">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Timestamp)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ApprovalStatus)

            </th>
            <th>
                @Html.DisplayNameFor(model => model.StartDate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.EndDate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Server.Cost)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Server)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.RequestedByUser)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.RequestJustification)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ApprovedByUser)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ApprovalComment)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td class="wrap">
                    @Html.DisplayFor(modelItem => item.Timestamp)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.ApprovalStatus)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.StartDate)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.EndDate)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Server.Cost)
                </td>
                <td class="wrap">
                    @if (!string.IsNullOrEmpty(item.Server.Hostname))
                    {
                        <div class="text-nowrap">Hostname: @Html.DisplayFor(modelItem => item.Server.Hostname)</div>
                    }
                    @if (!string.IsNullOrEmpty(item.Server.CPU))
                    {
                        <div class="text-nowrap">CPU: @Html.DisplayFor(modelItem => item.Server.CPU)</div>
                    }
                    @if (item.Server.HD != null)
                    {
                        <div class="text-nowrap">HD: @Html.DisplayFor(modelItem => item.Server.HDString)</div>
                    }
                    @if (item.Server.RAM != null)
                    {
                        <div class="text-nowrap">RAM: @Html.DisplayFor(modelItem => item.Server.RAMString)</div>
                    }
                    @if (!string.IsNullOrEmpty(item.Server.Hostname))
                    {
                        <div class="text-nowrap">@Html.DisplayFor(modelItem => item.Server.ServerType)</div>
                    }

                </td>
                <td class="wrap">
                    @Html.DisplayFor(modelItem => item.RequestedByEmployeeName)
                    @Html.DisplayFor(modelItem => item.RequestedByEmployeeId)
                    @Html.DisplayFor(modelItem => item.RequestedByUser.FullName)
                    @Html.DisplayFor(modelItem => item.RequestedByUser.EmployeeId)
                    @Html.DisplayFor(modelItem => item.RequestedByUser.Email)
                    @Html.DisplayFor(modelItem => item.RequestedByUser.PhoneNumber)
                </td>
                <td class="wrap">
                    @Html.DisplayFor(modelItem => item.RequestJustification)
                </td>
                <td class="wrap">
                    @Html.DisplayFor(modelItem => item.ApprovedByEmployeeName)
                    @Html.DisplayFor(modelItem => item.ApprovedByEmployeeId)
                    @Html.DisplayFor(modelItem => item.ApprovedByUser.FullName)
                    @Html.DisplayFor(modelItem => item.ApprovedByUser.EmployeeId)
                    @Html.DisplayFor(modelItem => item.ApprovedByUser.Email)
                    @Html.DisplayFor(modelItem => item.ApprovedByUser.PhoneNumber)
                </td>
                <td class="wrap">
                    @Html.DisplayFor(modelItem => item.ApprovalComment)
                </td>
                <td>
                    <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                    <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
                </td>
            </tr>
        }
    </tbody>
</table>

@section Scripts {
    <script src="~/js/request.js"></script>
}